apiVersion: v1
kind: ConfigMap
metadata:
  name: lesson-8-9-config
data:
  DEBUG: "True"
  SECRET_KEY: "your_secret_key"
  ALLOWED_HOSTS: "*"

  # DEBUG: "True"
  # SECRET_KEY: "your_secret_key"
  # DATABASE_URL: "postgres://lesson89user:14PtpSqm0L@lesson-8-9-db-postgresql.default.svc.cluster.local:5432/lesson89db"
  # DEBUG: "{{ .Values.env.DEBUG }}"
  # SECRET_KEY: "{{ .Values.env.SECRET_KEY }}"
  # DATABASE_URL: "{{ .Values.env.DATABASE_URL }}"


